name: DroneSwarm Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DroneSwarm
        uses: actions/checkout@v4
        with:
          path: DroneSwarm

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support kpartx wget unzip zip

      - name: Run Build Script
        run: |
          sudo bash DroneSwarm/builder/build.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Get Release Tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG_NAME=$(date +'%Y%m%d')-dev" >> $GITHUB_OUTPUT
          fi

      - name: Process Images
        run: |
          cd images
          for img in *.img; do
            if [ -f "$img" ]; then
              NEW_NAME="${img%.*}-${{ steps.get_tag.outputs.TAG_NAME }}.img"
              mv "$img" "$NEW_NAME"
              zip "${NEW_NAME%.*}.zip" "$NEW_NAME"
            fi
          done

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            images/*.img
            images/*.zip
